### ISSUE TITLE
Met PI_ERROR_OUT_OF_RESOURCES when run llama2-7b and gpt-j 6b via benchmark scripts all-in-one ipex_fp16_gpu continuously

### ISSUE THREAD

**Issue by Yanli2190** [intel-analytics/BigDL#9488]
/home/yanli/miniconda3/envs/ipex_ww44/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/home/yanli/miniconda3/envs/ipex_ww44/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.20s/it]
/home/yanli/miniconda3/envs/ipex_ww44/lib/python3.9/site-packages/intel_extension_for_pytorch/frontend.py:465: UserWarning: Conv BatchNorm folding failed during the optimize process.
  warnings.warn(
/home/yanli/miniconda3/envs/ipex_ww44/lib/python3.9/site-packages/intel_extension_for_pytorch/frontend.py:472: UserWarning: Linear BatchNorm folding failed during the optimize process.
  warnings.warn(
/home/yanli/miniconda3/envs/ipex_ww44/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:381: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/yanli/miniconda3/envs/ipex_ww44/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:386: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
>> loading of model costs 37.38696235002135s
<class 'transformers.models.llama.modeling_llama.LlamaForCausalLM'>
model generate cost: 2.4289329800230917
<s><s> Once upon a time, there was a young girl named Samantha who lived with her parents in a small town. Samantha had always dreamed of becoming a famous singer, but her parents were not very supportive of her dream. They wanted her to focus on her studies and get a "real"
model generate cost: 1.9140342809841968
<s><s> Once upon a time, there was a young girl named Samantha who lived with her parents in a small town. Samantha had always dreamed of becoming a famous singer, but her parents were not very supportive of her dream. They wanted her to focus on her studies and get a "real"
model generate cost: 1.9141055319923908
<s><s> Once upon a time, there was a young girl named Samantha who lived with her parents in a small town. Samantha had always dreamed of becoming a famous singer, but her parents were not very supportive of her dream. They wanted her to focus on her studies and get a "real"
model generate cost: 1.9145733139885124
<s><s> Once upon a time, there was a young girl named Samantha who lived with her parents in a small town. Samantha had always dreamed of becoming a famous singer, but her parents were not very supportive of her dream. They wanted her to focus on her studies and get a "real"
Traceback (most recent call last):
  File "/home/yanli/bigdl_perf/BigDL/python/llm/dev/benchmark/all-in-one/run.py", line 648, in <module>
    run_model(model, api, conf['in_out_pairs'], conf['local_model_hub'], conf['warm_up'], conf['num_trials'], conf['num_beams'], conf['low_bit'])
  File "/home/yanli/bigdl_perf/BigDL/python/llm/dev/benchmark/all-in-one/run.py", line 59, in run_model
    result = run_ipex_fp16_gpu(repo_id, local_model_hub, in_out_pairs, warm_up, num_trials, num_beams)
  File "/home/yanli/bigdl_perf/BigDL/python/llm/dev/benchmark/all-in-one/run.py", line 504, in run_ipex_fp16_gpu
    model = model.half().to('xpu')
  File "/home/yanli/miniconda3/envs/ipex_ww44/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2271, in to
    return super().to(*args, **kwargs)
  File "/home/yanli/miniconda3/envs/ipex_ww44/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/yanli/miniconda3/envs/ipex_ww44/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/yanli/miniconda3/envs/ipex_ww44/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/yanli/miniconda3/envs/ipex_ww44/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/yanli/miniconda3/envs/ipex_ww44/lib/python3.9/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/yanli/miniconda3/envs/ipex_ww44/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: Native API failed. Native API returns: -5 (PI_ERROR_OUT_OF_RESOURCES) -5 (PI_ERROR_OUT_OF_RESOURCES)
repo_id:
  - 'meta-llama/Llama-2-7b-chat-hf'
  #- 'meta-llama/Llama-2-13b-chat-hf'
  #- 'meta-llama/Llama-2-70b-chat-hf'
  - 'EleutherAI/gpt-j-6B'
  #-  'facebook/opt-6.7b'
  #- 'facebook/opt-30b'
  #- 'THUDM/chatglm2-6b'
  #- 'tiiuae/falcon-7b-instruct-with-patch'
  #- 'tiiuae/falcon-40b-instruct'
local_model_hub: 'path to your local model hub'
#local_model_hub: '/home/yanli/.cache/huggingface/hub'
warm_up: 1
num_trials: 3
num_beams: 1 # default to greedy search
low_bit: 'sym_int4' # default to use 'sym_int4' (i.e. symmetric int4)
in_out_pairs:
  - '32-32'
  #- '1024-128'
  #- '1024-1024'
  #- '2048-256'
  #- '2048-2048'
test_api:
  #- "transformer_int4"
  #- "native_int4"
  #- "optimize_model"
  #- "pytorch_autocast_bf16"
  - "ipex_fp16_gpu" # on Intel GPU
  # - "transformer_int4_gpu"  # on Intel GPU
  # - "optimize_model_gpu"  # on Intel GPU
  # - "deepspeed_transformer_int4_cpu" # on Intel SPR Server

**Comment by hkvision** [comment]
@WeiguangHan Please check this issue.

**Comment by Yanli2190** [comment]
[1.log](https://github.com/intel-analytics/BigDL/files/13405723/1.log)
Full log including config.yaml

**Comment by WeiguangHan** [comment]
> [1.log](https://github.com/intel-analytics/BigDL/files/13405723/1.log) Full log including config.yaml

Thanks for your log. I can produce it on my side. This issue is caused by the failure to release the memory occupied by the previous model `Llama-2-7b-chat-hf` in a timely manner while running the `gpt-j-6B` model although the `torch.xpu.empty_cache()` exists in `run_ipex_fp16_gpu` function. I am currently searching for the reason.

**Comment by WeiguangHan** [comment]
`torch.xpu.empty_cache()` doesn't seem to be able to release gpu memory timely. The issue can be resolved by this PR https://github.com/intel-analytics/BigDL/pull/9504 which uses `del model` to release the occupied memory.

**Comment by hkvision** [comment]
@rnwang04 Could you help confirm this? Have you tested two models together when you run ipex_fp16?

**Comment by rnwang04** [comment]
@hkvision I kind of forgot if I had run multiple fp16 consecutively at that time.. But this pr LGTM and I have confirmed it works on my side.

**Comment by hkvision** [comment]
@Yanli2190 We have fixed this issue, could you please use the latest benchmark script to re-check this?

**Comment by Yanli2190** [comment]
I have verified and confirme that it works well
